Feat/add support for install
SwarmUS/HiveMindBridge pull request #1
Opened 2021-04-10 18:33 UTC by stlaperriere

Initial build system that allows for installation and usage with `find_package()`.

This contains a build system that enables a user to install HiveMindBridge on his system. Installing HiveMindBridge also installs Propolis-cpp-common and Propolis-pheromones, as well as Pheromones. The user must install nanopb by himself (**by following the instructions in the readme**). 

Normally, this should not break anything on your system. I had some problems with nanopb, so I had to fork their repo and fiddle with the installation commands. I removed what caused the problems. **Just to make sure that your system does not break, I recommend testing this in a Docker container first. When you see that everything works, try it on your host machine.**

To test that everything works, just go through the instructions in the readme, and create a test project that links against the various libraries (`swarmus-hivemind-bridge`, `swarmus-propolis-cpp-common`, `swarmus-propolis-pheromones`)

2021-04-11 21:26 UTC, g-lesssard requested changes
Good job, minor comments for ease of use,

2021-04-11 21:26 UTC, g-lesssard commented on README.md
> +HiveMindBridge relies on nanopb underneath for the serialization and deserialization of Protobuf messages. For a better integration with the build system, SwarmUS has forked the nanopb repository. Yo
Could we add our nanopb fork as a CMake module so the user only has one repo to clone?

2021-04-11 21:26 UTC, g-lesssard commented on README.md
> +target_link_libraries(myTestExecutable swarmus-hivemind-bridge)
target_link_libraries requires the keyword PRIVATE or PUBLIC before specifying the libraries to link

2021-04-11 21:26 UTC, g-lesssard commented on README.md
> +(cat install_manifest.txt; echo) | sudo sh -c 'while read i ; do rm "$i" ; rmdir --ignore-fail-on-non-empty -p "${i%/*}" ; done'
You could create a cmake custom_target for this call. This way instead of having to copy and paste this line, the user could only call ```sudo make uninstall```. I belive this should work:

```cmake
add_custom_target(uninstall
(COMMAND cat install_manifest.txt; echo) | sudo sh -c 'while read i ; do rm "$i" ; rmdir --ignore-fail-on-non-empty -p "${i%/*}" ; done')
```

2021-04-11 22:10 UTC, xgroleau requested changes
Small nitpick in the readme and artifact that comes from the hivemind

2021-04-11 22:10 UTC, xgroleau commented on CMakeLists.txt
> +#googletest_fetch_populate()
Won't this be necessary to test since we don't have ROS in this repo?

2021-04-11 22:10 UTC, xgroleau commented on README.md
> +(cat install_manifest.txt; echo) | sudo sh -c 'while read i ; do rm "$i" ; rmdir --ignore-fail-on-non-empty -p "${i%/*}" ; done'
I would definitly advise against making a custom command that calls sudo, in particular one that removes file with a while, the user could endup with a broken system. Also in the readme generally the instruction for uninstalling are not written, but if you want to write them, we could use `xargs rm < install_manifest.txt` instead of the while loop, which is how it's done normally.

2021-04-11 22:10 UTC, xgroleau commented on README.md
> +## Requirements
Write the minimum c++ version in the readme

2021-04-11 22:10 UTC, xgroleau commented on cmake/doc/doxygen.cmake
> +        "*/decawave/driver/*")
No need for the hal and deca

2021-04-11 22:10 UTC, xgroleau commented on cmake/doc/doxygen.cmake
> +    endif()
No need for posix and stm32

2021-04-11 22:10 UTC, xgroleau commented on cmake/doc/doxygen.cmake
> +        COMMENT "Generate HiveMind documentation")
HiveMindBridge

2021-04-12 12:19 UTC, stlaperriere commented on README.md
> +(cat install_manifest.txt; echo) | sudo sh -c 'while read i ; do rm "$i" ; rmdir --ignore-fail-on-non-empty -p "${i%/*}" ; done'
The `xargs rm < install_manifest.txt` command removes the files, but not the directories. But is that a more standard way? Idk it seems weird to me that "uninstalling" would not remove the folders, it's confusing.

2021-04-12 12:22 UTC, stlaperriere commented on CMakeLists.txt
> +#googletest_fetch_populate()
Yes, as I mentioned in the PR description, I'll enable the tests in my next PR.

2021-04-12 12:29 UTC, stlaperriere commented on README.md
> +HiveMindBridge relies on nanopb underneath for the serialization and deserialization of Protobuf messages. For a better integration with the build system, SwarmUS has forked the nanopb repository. Yo
Actually, it's already done by Pheromones, and calling `make install` on HiveMindBridge already installs everything. I'll just remove those instructions.

2021-04-12 12:31 UTC, stlaperriere commented on README.md
> +target_link_libraries(myTestExecutable swarmus-hivemind-bridge)
It is not required.

https://cmake.org/cmake/help/latest/command/target_link_libraries.html

2021-04-12 12:36 UTC, stlaperriere commented on README.md
> +(cat install_manifest.txt; echo) | sudo sh -c 'while read i ; do rm "$i" ; rmdir --ignore-fail-on-non-empty -p "${i%/*}" ; done'
Anyway, I'll just add an `uninstall` target that calls `xargs rm < install_manifest.txt`.

2021-04-12 12:57 UTC, g-lesssard commented on README.md
> +target_link_libraries(myTestExecutable swarmus-hivemind-bridge)
My bad... I remember having issues when not specifying this, but it must have been for something else

2021-04-12 12:59 UTC, g-lesssard approved these changes

2021-04-12 14:07 UTC, xgroleau approved these changes

2021-04-12 14:11 UTC, merged